name: pigeon_build_core
description: A core package for pigeon_build_runner
version: 1.0.0
homepage: https://github.com/rotorgames/pigeon_build_runner
repository: https://github.com/rotorgames/pigeon_build_runner/tree/main/packages/pigeon_build_core
issue_tracker: https://github.com/rotorgames/pigeon_build_runner/issues

environment:
  sdk: '>=2.18.4 <4.0.0'

dependencies:
  path: ^1.8.2
  meta: ^1.9.1
  recase: ^4.1.0
  pigeon: ^10.0.0
  pigeon_build_config: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependency_overrides:
  pigeon_build_config:
    path: ../pigeon_build_config