name: pigeon_build_runner
description: Seamlessly integrate pigeon with build_runner for efficient code generation and streamlined development.
homepage: https://github.com/rotorgames/pigeon_build_runner
repository: https://github.com/rotorgames/pigeon_build_runner
issue_tracker: https://github.com/rotorgames/pigeon_build_runner/issues
documentation: https://github.com/rotorgames/pigeon_build_runner/blob/main/README.md
version: 2.0.0

environment:
  sdk: '>=2.18.4 <4.0.0'

dependencies:
  pigeon_build_config: ^1.1.0
  pigeon_build_core: ^2.0.0
  build: ^2.4.2
  pigeon: ">=24.0.0"
  scratch_space: ^1.0.2
  path: ^1.9.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
