name: pigeon_build_runner
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  pigeon_build_config: ^1.0.0
  pigeon_build_core: ^1.0.0
  build: ^2.4.0
  pigeon: ^10.0.0
  scratch_space: ^1.0.0
  path: ^1.8.3

dependency_overrides: 
  pigeon_build_core: 
    path: ../pigeon_build_core
  pigeon_build_config: 
    path: ../pigeon_build_config

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
