name: pigeon_build_runner
description: Seamlessly integrate 'pigeon' with 'build_runner' for efficient code generation and streamlined development.
homepage: https://github.com/rotorgames/pigeon_build_runner
repository: https://github.com/rotorgames/pigeon_build_runner/tree/main/packages/pigeon_build_core
issue_tracker: https://github.com/rotorgames/pigeon_build_runner/issues
documentation: https://github.com/rotorgames/pigeon_build_runner/blob/main/packages/pigeon_build_runner/README.md
version: 1.0.1

environment:
  sdk: '>=2.18.4 <4.0.0'

dependencies:
  pigeon_build_config: ^1.0.0
  pigeon_build_core: ^1.0.0
  build: ^2.4.0
  pigeon: ^10.0.0
  scratch_space: ^1.0.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
