name: pigeon_build_runner_example
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '^3.0.0'
  flutter: ">=3.10.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1

dependency_overrides: 
  pigeon_build_runner: 
    path: ../
  pigeon_build_core: 
    path: ../../pigeon_build_core
  pigeon_build_config: 
    path: ../../pigeon_build_config

dev_dependencies:
  pigeon_build_runner: ^2.0.0
  pigeon: ^25.3.0
  build_runner: ^2.4.15
  lints: ^5.1.1
  test: ^1.25.15

pigeon:
  main-input:
    input: pigeons/
    dart:
      out: out/dart
      test-out: out/test/
    ast:
      out: out/ast
    objc:
      header-out: out/objc
      source-out: out/objc
      prefix: example
    java:
      out: out/java
      package: dev.flutter.pigeon_example_app
    swift:
      out: out/swift
    kotlin:
      out: out/kotlin
      package: dev.flutter.pigeon_example_app
    cpp:
      header-out: out/cpp
      source-out: out/cpp
      namespace: CppNamespace
  inputs:
    - input: example_file.dart
      dart:
        out: example_file.dart
        test-out: example_file.dart
      ast:
        out: example_file.dart
      objc:
        header-out: ExampleFile.h
        source-out: ExampleFile.m
        prefix: example
      java:
        out: ExampleFile.java
        package: .examples
      swift:
        out: ExampleFile.swift
      kotlin:
        out: ExampleFile.kt
        package: .example
      cpp:
        header-out: example_file.h
        source-out: example_file.cpp
        namespace: NewNamespace