name: pigeon_build_config
description: A config package for pigeon_build_runner
version: 1.0.0
homepage: https://github.com/rotorgames/pigeon_build_runner
repository: https://github.com/rotorgames/pigeon_build_runner
issue_tracker: https://github.com/rotorgames/pigeon_build_runner/issues
documentation: https://github.com/rotorgames/pigeon_build_runner/blob/main/README.md

environment:
  sdk: '>=2.18.4 <4.0.0'

dependencies:
  checked_yaml: ^2.0.1
  json_annotation: ^4.8.1

dev_dependencies:
  json_serializable: ^6.7.0
  build_runner: ^2.3.2
  lints: ^2.0.0
  test: ^1.16.0
