name: pigeon_build_config
description: A config package for pigeon_build_runner
version: 1.1.0
homepage: https://github.com/rotorgames/pigeon_build_runner
repository: https://github.com/rotorgames/pigeon_build_runner
issue_tracker: https://github.com/rotorgames/pigeon_build_runner/issues
documentation: https://github.com/rotorgames/pigeon_build_runner/blob/main/README.md

environment:
  sdk: '>=2.18.4 <4.0.0'

dependencies:
  checked_yaml: ^2.0.3
  json_annotation: ^4.9.0

dev_dependencies:
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  lints: ^5.1.1
  test: ^1.25.15
