name: pigeon_build_config
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.4 <4.0.0'

dependencies:
  checked_yaml: ^2.0.1
  json_annotation: ^4.8.1

dev_dependencies:
  json_serializable: ^6.7.0
  build_runner: ^2.3.2
  lints: ^2.0.0
  test: ^1.16.0
