name: pigeon_build_config
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment: 
  sdk: '>=2.18.4 <4.0.0'

pigeon:
  main-input:
    copyright-header: pigeons/copyright.txt
    one-language: true
    debug-generators: true

    input: pigeons/

    dart:
      out: 'test'
      test-out: test/pigeons/
    ast:
      out: lib/ast/ast/
    objc:
      header-out: out/test/
      source-out: out/test/
      prefix: example
    java:
      out: android/app/src/main/java/dev/flutter/pigeon_example_app/pigeons
      package: dev.flutter.pigeon_example_app
      use-generated-annotation: true
    swift:
      out: ios/Runner/Pigeons
    kotlin:
      out: android/app/src/main/kotlin/dev/flutter/pigeon_example_app/pigeons
      package: dev.flutter.pigeon_example_app
    cpp:
      header-out: windows/runner/pigeons
      source-out: windows/runner/pigeons
      namespace: CppNamespace
  inputs:
    - copyright-header: pigeons/copyright.txt
      one-language: true
      debug-generators: true

      input: pigeons/

      dart:
        out: lib/src/pigeons/
        test-out: test/pigeons/
      ast:
        out: lib/ast/ast/
      objc:
        header-out: out/test/
        source-out: out/test/
        prefix: example
      java:
        out: android/app/src/main/java/dev/flutter/pigeon_example_app/pigeons
        package: dev.flutter.pigeon_example_app
        use-generated-annotation: true
      swift:
        out: ios/Runner/Pigeons
      kotlin:
        out: android/app/src/main/kotlin/dev/flutter/pigeon_example_app/pigeons
        package: dev.flutter.pigeon_example_app
      cpp:
        header-out: windows/runner/pigeons
        source-out: windows/runner/pigeons
        namespace: CppNamespace